RefTemeto/Models/Redemption.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RefTemeto.Models
{
    public class Redemption     //megváltások
    {
        [Key]
        [DisplayName("Megváltásazonosító")]
        public int RedemptionId { get; set; }

        [DisplayName("Megváltott sírhely")]
        [Required]
        public int RedemptionGraveId { get; set; }

        [DisplayName("Megváltó személy")]
        [Required]
        public int RedemptionRenterId { get; set; }
        
        [DisplayName("Sírgondozó személy")]
        [Required]
        public int RedemptionTenderId { get; set; }

        [DisplayName("Sírmegváltás időpontja")]
        [Required]
        public DateTime RedemptionDate { get; set; }

        [DisplayName("Sírmegváltás időtartama (év)")]
        [Required]
        [Range(1, int.MaxValue)]
        public int RedemptionPeriod { get; set; }


        [ForeignKey("RedemptionGraveId")]
        public virtual Grave Grave { get; set; }   //Ez a csatolt tábla sír tábla

        [ForeignKey("RedemptionRenterId")]
        public virtual Renter Renter { get; set; }   //Ez a csatolt tábla sírmegváltó tábla

        [ForeignKey("RedemptionTenderId")]
        public virtual Renter Tender { get; set; }   //Ez a csatolt tábla sírgondozó tábla megegyezik a sírmegváltóval
    }
}

RefTemeto/Controllers/RedemptionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RefTemeto.Data;
using RefTemeto.Models;
using RefTemeto.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RefTemeto.Controllers
{
    public class RedemptionController : Controller
    {
        private readonly ApplicationDbContext _db;
        public RedemptionController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Redemption> objList = _db.Redemptions;
            foreach (var obj in objList)         // Ez kell a típusok megjelenítéséhez
            {
                obj.Grave= _db.Graves.FirstOrDefault(u => u.GraveId == obj.RedemptionGraveId);
                obj.Renter = _db.Renters.FirstOrDefault(u => u.RenterId == obj.RedemptionRenterId);
                obj.Tender = _db.Renters.FirstOrDefault(u => u.RenterId == obj.RedemptionTenderId);
            }
            return View(objList);
        }

        //GET-CREATE
        public IActionResult Create()
        {
            //IEnumerable<SelectListItem> TypeDropDown = _db.Settlements.Select(i => new SelectListItem
            //{
            //    Text = i.Station + "  " +i.PostalCode.ToString(),
            //    Value = i.SettlementId.ToString()
            //}) ;
            //ViewBag.TypeDropDown = TypeDropDown;

            RedemptionVM redemptionVM = new RedemptionVM()
            {
                Redemption = new Redemption(),
                TypeDropDownGrave = _db.Graves.Select(i => new SelectListItem
                {
                    Text = i.GraveType + " típus, " + i.Parcel+" parcella," +i.Row+ ", sor" +i.Side+" oldal, "+i.Size+" méret",
                    Value = i.GraveId.ToString()
                }),

                 TypeDropDownRenter = _db.Renters.Select(i => new SelectListItem
                 {
                     Text = i.RenterLastname+" "+ i.RenterFirstname +" telefonszám: " +i.RenterPhoneNumber ,
                     Value = i.RenterId.ToString()
                 }),

                  TypeDropDownTender = _db.Renters.Select(i => new SelectListItem
                  {
                      Text = i.RenterLastname+" " + i.RenterFirstname + " telefonszám: " + i.RenterPhoneNumber,
                      Value = i.RenterId.ToString()
                  })
            };
            return View(redemptionVM);
        }
        
        //Post-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RedemptionVM obj)
        {
            if (ModelState.IsValid)
            {
                _db.Redemptions.Add(obj.Redemption);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        public IActionResult Edit(int? id)
        {
            RedemptionVM redemptionVM = new RedemptionVM()
            {
                Redemption = new Redemption(),
                TypeDropDownGrave = _db.Graves.Select(i => new SelectListItem
                {
                    Text = i.GraveType + " típus, " + i.Parcel + " parcella," + i.Row + ", sor" + i.Side + " oldal, " + i.Size + " méret",
                    Value = i.GraveId.ToString()
                }),

                TypeDropDownRenter = _db.Renters.Select(i => new SelectListItem
                {
                    Text = i.RenterLastname + " " + i.RenterFirstname + " telefonszám: " + i.RenterPhoneNumber,
                    Value = i.RenterId.ToString()
                }),

                TypeDropDownTender = _db.Renters.Select(i => new SelectListItem
                {
                    Text = i.RenterLastname + " " + i.RenterFirstname + " telefonszám: " + i.RenterPhoneNumber,
                    Value = i.RenterId.ToString()
                })
            };

            if (id == null || id == 0)
            {
                return NotFound();
            }

            redemptionVM.Redemption = _db.Redemptions.Find(id);
            if (redemptionVM.Redemption == null)
            {
                return NotFound();
            }

            return View(redemptionVM);
        }
                                                                                                                                                                                                                                                                                                                                                                            

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post Edit
        public IActionResult Edit(RedemptionVM obj)
        {
            if (ModelState.IsValid)
            {
                _db.Redemptions.Update(obj.Redemption);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // Get Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id < 1)
            {
                return NotFound();
            }
            var obj = _db.Redemptions.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post Delete
        public IActionResult DeletePost(int? RedemptionId)
        {
            var obj = _db.Redemptions.Find(RedemptionId);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Redemptions.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RefTemeto/Views/Redemption/Create.cshtml
@model RefTemeto.Models.ViewModels.RedemptionVM

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Sírmegváltás felvétele</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionGraveId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Redemption.RedemptionGraveId" asp-items="@Model.TypeDropDownGrave" class="form-control">
                            <option selected>-- Válasszon sírhelyet!--</option>
                        </select>
                        <span asp-validation-for="Redemption.RedemptionGraveId" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionRenterId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Redemption.RedemptionRenterId" asp-items="@Model.TypeDropDownRenter" class="form-control">
                            <option selected>-- Válasszon sírmegváltó személyt!--</option>
                        </select>
                        <span asp-validation-for="Redemption.RedemptionRenterId" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionTenderId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Redemption.RedemptionTenderId" asp-items="@Model.TypeDropDownTender" class="form-control">
                            <option selected>-- Válasszon sírgondozó személyt!--</option>
                        </select>
                        <span asp-validation-for="Redemption.RedemptionTenderId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Redemption.RedemptionDate" class="form-control" />
                        <span asp-validation-for="Redemption.RedemptionDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionPeriod"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Redemption.RedemptionPeriod" class="form-control" />
                        <span asp-validation-for="Redemption.RedemptionPeriod" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Készít" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>

    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Redemption/Delete.cshtml
@model RefTemeto.Models.Redemption

<form method="post" asp-action="DeletePost">
    <input asp-for="RedemptionId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Sírmegváltás törlése</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RedemptionDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RedemptionDate" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RedemptionPeriod"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RedemptionPeriod" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Töröl" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Redemption/Edit.cshtml
@model RefTemeto.Models.ViewModels.RedemptionVM

<form method="post">
    <input asp-for="Redemption.RedemptionId" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Sírmegváltás módosítása</h2>
        </div>
        <div class="row">
            <div class="col-8">

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionGraveId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Redemption.RedemptionGraveId" asp-items="@Model.TypeDropDownGrave" class="form-control">
                            <option selected>-- Válasszon sírhelyet!--</option>
                        </select>
                        <span asp-validation-for="Redemption.RedemptionGraveId" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionRenterId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Redemption.RedemptionRenterId" asp-items="@Model.TypeDropDownRenter" class="form-control">
                            <option selected>-- Válasszon sírmegváltó személyt!--</option>
                        </select>
                        <span asp-validation-for="Redemption.RedemptionRenterId" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionTenderId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Redemption.RedemptionTenderId" asp-items="@Model.TypeDropDownTender" class="form-control">
                            <option selected>-- Válasszon sírgondozó személyt!--</option>
                        </select>
                        <span asp-validation-for="Redemption.RedemptionTenderId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Redemption.RedemptionDate" class="form-control" />
                        <span asp-validation-for="Redemption.RedemptionDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Redemption.RedemptionPeriod"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Redemption.RedemptionPeriod" class="form-control" />
                        <span asp-validation-for="Redemption.RedemptionPeriod" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Frissít" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>

    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Redemption/Index.cshtml
@model IEnumerable<RefTemeto.Models.Redemption>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Megváltások listája</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Redemption" asp-action="Create" class="btn btn-primary">
                Új megváltás felvétele
            </a>
        </div>
    </div>
    <br /> <br />

    @if (Model.Count() > 0)
    {
        <table class="table-bordered table-striped" style="width: 100%">
            <thead>
                <tr>
                    <th>
                        Sírgondozó személy
                    </th>
                    <th>
                        Sírhely
                    </th>
                    <th>
                        Megváltó személy
                    </th>
                    <th>
                        Megváltás időpontja
                    </th>
                    <th>
                        Megváltás időtartama(év)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="15%"> @obj.Tender.RenterLastname @obj.Tender.RenterFirstname   </td>
                    <td width="15%"> @obj.Grave.Row. sor, @obj.Grave.Side oldal, @obj.Grave.Parcel. parcella, @obj.Grave.GraveType típus, @obj.Grave.Size méret </td>
                    <td width="15%"> @obj.Renter.RenterLastname @obj.Renter.RenterFirstname  </td>
                    <td width="15%"> @obj.RedemptionDate       </td>
                    <td width="15%"> @obj.RedemptionPeriod   </td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Redemption" asp-route-Id="@obj.RedemptionId" asp-action="Edit" class="btn btn-primary mx-2">
                                Szerkeszt
                            </a>
                            <a asp-controller="Redemption" asp-route-Id="@obj.RedemptionId" asp-action="Delete" class="btn btn-danger mx-2">
                                Töröl
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Nincsenek rögzített sírmegváltások.</p>
    }
</div>