RefTemeto/Models/Renter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RefTemeto.Models
{
    public class Renter         //Sírbérlő, megváltó
    {
        [Key]
        [DisplayName("Azonosító")]
        public int RenterId { get; set; }

        [Required]
        [DisplayName("Vezetéknév")]
        public string RenterLastname{ get; set; }

        [Required]
        [DisplayName("Keresztnév")]
        public string RenterFirstname { get; set; }

        [Required]
        [Range(1, int.MaxValue)]
        [DisplayName("Település")]
         public int RenterSettlementId { get; set; }

        [Required]
        [DisplayName("Cím")]
        public string RenterAdress { get; set; }

        [DisplayName("e-mail")]
        [EmailAddress]
        public string RenterEmail { get; set; }

        [DisplayName("telefon")]
        [Phone]
        public string RenterPhoneNumber { get; set; }

        [ForeignKey("RenterSettlementId")]
        public virtual Settlement Settlement { get; set; }   //Ez a csatolt tábla
    }
}

RefTemeto/Controllers/RenterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RefTemeto.Data;
using RefTemeto.Models;
using RefTemeto.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RefTemeto.Controllers
{
    public class RenterController : Controller
    {
        private readonly ApplicationDbContext _db;
        public RenterController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Renter> objList = _db.Renters;
            foreach (var obj in objList)         // Ez kell a típusok megjelenítéséhez
            {
                obj.Settlement= _db.Settlements.FirstOrDefault(u => u.SettlementId == obj.RenterSettlementId);
            }
            return View(objList);
        }

        //GET-CREATE
        public IActionResult Create()
        {
            //IEnumerable<SelectListItem> TypeDropDown = _db.Settlements.Select(i => new SelectListItem
            //{
            //    Text = i.Station + "  " +i.PostalCode.ToString(),
            //    Value = i.SettlementId.ToString()
            //}) ;
            //ViewBag.TypeDropDown = TypeDropDown;

            RenterVM renterVM = new RenterVM()
            {
                Renter = new Renter(),
                TypeDropDown = _db.Settlements.Select(i => new SelectListItem
                {
                    Text = i.Station + "  " + i.PostalCode.ToString(),
                    Value = i.SettlementId.ToString()
                })
            };
            return View(renterVM);
        }
        
        //Post-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RenterVM obj)
        {
            if (ModelState.IsValid)
            {
                _db.Renters.Add(obj.Renter);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        public IActionResult Edit(int? id)
        {
            RenterVM renterVM = new RenterVM()
            {
                Renter = new Renter(),
                TypeDropDown = _db.Settlements.Select(i => new SelectListItem
                {
                    Text = i.Station + "  " + i.PostalCode.ToString(),
                    Value = i.SettlementId.ToString()
                })
            };

            if (id == null || id == 0)
            {
                return NotFound();
            }

            renterVM.Renter = _db.Renters.Find(id);
            if (renterVM.Renter == null)
            {
                return NotFound();
            }

            return View(renterVM);
        }
                                                                                                                                                                                                                                                                                                                                                                            

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post Edit
        public IActionResult Edit(RenterVM obj)
        {
            if (ModelState.IsValid)
            {
                _db.Renters.Update(obj.Renter);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // Get Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id < 1)
            {
                return NotFound();
            }
            var obj = _db.Renters.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post Delete
        public IActionResult DeletePost(int? RenterId)
        {
            var obj = _db.Renters.Find(RenterId);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Renters.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RefTemeto/Views/Renter/Create.cshtml
@model RefTemeto.Models.ViewModels.RenterVM

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Sírmegváltó / gondozó személy felvétele</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterLastname"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterLastname" class="form-control" />
                        <span asp-validation-for="Renter.RenterLastname" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterFirstname"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterFirstname" class="form-control" />
                        <span asp-validation-for="Renter.RenterFirstname" class="text-danger"></span>
                    </div>
                </div> 
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterSettlementId"></label>
                    </div>
                    <div class="col-3">
                        <select asp-for="Renter.RenterSettlementId" asp-items="@Model.TypeDropDown" class="form-control" >
                        <option selected>-- Válasszon települést!--</option>
                        </select>
                        <span asp-validation-for="Renter.RenterSettlementId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterAdress"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterAdress" class="form-control" />
                        <span asp-validation-for="Renter.RenterAdress" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterEmail"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterEmail" class="form-control" />
                        <span asp-validation-for="Renter.RenterEmail" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterPhoneNumber"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterPhoneNumber" class="form-control" />
                        <span asp-validation-for="Renter.RenterPhoneNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Készít" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>

    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Renter/Delete.cshtml
@model RefTemeto.Models.Renter

<form method="post" asp-action="DeletePost">
    <input asp-for="RenterId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Sírmegváltó / gondozó törlése</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RenterLastname"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RenterLastname" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RenterFirstname"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RenterFirstname" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RenterEmail"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RenterEmail" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="RenterPhoneNumber"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="RenterPhoneNumber" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Töröl" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Renter/Edit.cshtml
@model RefTemeto.Models.ViewModels.RenterVM

<form method="post">
    <input asp-for="Renter.RenterId" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Sírmegváltó/gondozó módosítása</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterLastname"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterLastname" class="form-control" />
                        <span asp-validation-for="Renter.RenterLastname" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterFirstname"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterFirstname" class="form-control" />
                        <span asp-validation-for="Renter.RenterFirstname" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterSettlementId"></label>
                    </div>
                    <div class="col-3">
                        <select asp-for="Renter.RenterSettlementId" asp-items="@Model.TypeDropDown" class="form-control">
                            <option selected>-- Válasszon települést!--</option>
                        </select>
                        <span asp-validation-for="Renter.RenterSettlementId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterAdress"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterAdress" class="form-control" />
                        <span asp-validation-for="Renter.RenterAdress" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterEmail"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterEmail" class="form-control" />
                        <span asp-validation-for="Renter.RenterEmail" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Renter.RenterPhoneNumber"></label>
                    </div>
                    <div class="col-3">
                        <input asp-for="Renter.RenterPhoneNumber" class="form-control" />
                        <span asp-validation-for="Renter.RenterPhoneNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Frissít" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>

    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Renter/Index.cshtml
@model IEnumerable<RefTemeto.Models.Renter>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Sírmegváltók / gondozók listája</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Renter" asp-action="Create" class="btn btn-primary">
                Új sírmegváltó / gondozó felvétele
            </a>
        </div>
    </div>
    <br /> <br />

    @if (Model.Count() > 0)
    {
        <table class="table-bordered table-striped" style="width: 100%">
            <thead>
                <tr>
                    <th>
                        Vezetéknév
                    </th>
                    <th>
                        Keresztnév
                    </th>
                    <th>
                        Település
                    </th>
                    <th>
                        Irányítószám
                    </th>
                    <th>
                        Cím
                    </th>
                    <th>
                        e-mail
                    </th>
                    <th>
                        telefon
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="20%"> @obj.RenterLastname   </td>
                    <td width="20%"> @obj.RenterFirstname  </td>
                    <td width="10%"> @obj.Settlement.Station  </td>
                    <td width="10%"> @obj.Settlement.PostalCode  </td>
                    <td width="10%"> @obj.RenterAdress    </td>
                    <td width="10%"> @obj.RenterEmail     </td>
                    <td width="10%"> @obj.RenterPhoneNumber     </td>
                    <td class="text-center">
                        <div class="w-100 btn-group" role="group">
                            <a asp-controller="Renter" asp-route-Id="@obj.RenterId" asp-action="Edit" class="btn btn-primary mx-2">
                                Szerkeszt
                            </a>
                            <a asp-controller="Renter" asp-route-Id="@obj.RenterId" asp-action="Delete" class="btn btn-danger mx-2">
                                Töröl
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Nincsenek rögzített sírmegváltó személyek.</p>
    }
</div>