RefTemeto/Models/Dead.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RefTemeto.Models
{
  
    public class Dead          // Halott 
    {
        [Key]
        [DisplayName("Azonosító")]
        public int DeadId { get; set; }

        [Required]
        [DisplayName("Születési vezetéknév")]
        public string DeadBirthLastName { get; set; }
        
        [Required]
        [DisplayName("Születési keresztnév")]
        public string DeadBirthFirstName { get; set; }

        [Required]
        [DisplayName("Anyja neve")]
        public string DeadMothersName { get; set; }

        [DisplayName("Születési hely")]
        public int DeadBirthSettlementId { get; set; }

        [DisplayName("Születési dátum")]
        public DateTime DeadBirthDate { get; set; }

        [DisplayName("Elhalálozás dátuma")]
        public DateTime DeadDeathDate { get; set; }

        [DisplayName("Vallás")]
        [Required]
        public int DeadReligionId { get; set; }

        [DisplayName("Halál oka")]
        public string DeadCauseOfDeath { get; set; }
        
        [DisplayName("Sírhely")]
        [Required]
        public int DeadGraveId { get; set; }

        [DisplayName("Temetés")]
        [Required]
        public int DeadBurialId { get; set; }


        [ForeignKey("DeadReligionId")]
        public virtual Religion Religion { get; set; }   //Ez a csatolt tábla sír tábla

        [ForeignKey("DeadGraveId")]
        public virtual Grave Grave { get; set; }   //Ez a csatolt tábla sír tábla

        [ForeignKey("DeadBurialId")]
        public virtual Burial Burial { get; set; }   //Ez a csatolt tábla temetés tábla
        
        [ForeignKey("DeadBirthSettlementId")]
        public virtual Settlement Settlement { get; set; }   //Ez a csatolt tábla születési hely tábla
    }
}

RefTemeto/Controllers/DeadController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RefTemeto.Data;
using RefTemeto.Models;
using RefTemeto.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RefTemeto.Controllers
{
    public class DeadController : Controller
    {
        private readonly ApplicationDbContext _db;
        public DeadController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Dead> objList = _db.Deads;
            foreach (var obj in objList)         // Ez kell a típusok megjelenítéséhez
            {
                obj.Religion = _db.Religions.FirstOrDefault(u => u.ReligionId == obj.DeadReligionId);
                obj.Grave= _db.Graves.FirstOrDefault(u => u.GraveId == obj.DeadGraveId);
                obj.Burial = _db.Burials.FirstOrDefault(u => u.FuneralId == obj.DeadBurialId);
                obj.Settlement = _db.Settlements.FirstOrDefault(u => u.SettlementId == obj.DeadBirthSettlementId);
            }
            return View(objList);
        }

        //GET-CREATE
        public IActionResult Create()
        {
            DeadVM deadVM = new DeadVM()
            {
                Dead= new Dead(),
                TypeDropDownGrave = _db.Graves.Select(i => new SelectListItem
                {
                    Text = i.GraveType + ". típus, " + i.Parcel+". parcella, " +i.Row+ ", sor " +i.Side+" oldal, "+i.Size+" méret",
                    Value = i.GraveId.ToString()
                }),

                 TypeDropDownBurial = _db.Burials.Select(i => new SelectListItem
                 {
                     Text = "temettető: "+i.FuneralName+ ", időpont: "+ i.FuneralDateTime,
                     Value = i.FuneralId.ToString()
                 }),

                  TypeDropDownSettlement = _db.Settlements.Select(i => new SelectListItem
                  {
                      Text = i.Station+" "+ i.PostalCode,
                      Value = i.SettlementId.ToString()
                  }),

                  TypeDropDownReligion = _db.Religions.Select(i => new SelectListItem
                  {
                      Text = i.ReligionName,
                      Value = i.ReligionId.ToString()
                  })
            };
            return View(deadVM);
        }
        
        //Post-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DeadVM obj)
        {
            if (ModelState.IsValid)
            {
                _db.Deads.Add(obj.Dead);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        public IActionResult Edit(int? id)
        {
             DeadVM deadVM = new DeadVM()
            {
                Dead= new Dead(),
                TypeDropDownGrave = _db.Graves.Select(i => new SelectListItem
                {
                    Text = i.GraveType + " típus, " + i.Parcel+". parcella, " +i.Row+ ". sor, " +i.Side+" oldal, "+i.Size+" méret",
                    Value = i.GraveId.ToString()
                }),

                 TypeDropDownBurial = _db.Burials.Select(i => new SelectListItem
                 {
                     Text = "temettető: "+i.FuneralName+ ", időpont: "+ i.FuneralDateTime +", Temetkezési vállalat: " +i.Undertaker ,
                     Value = i.FuneralId.ToString()
                 }),

                  TypeDropDownSettlement = _db.Settlements.Select(i => new SelectListItem
                  {
                      Text = i.Station+" "+ i.PostalCode,
                      Value = i.SettlementId.ToString()
                  }),

                 TypeDropDownReligion = _db.Religions.Select(i => new SelectListItem
                 {
                     Text = i.ReligionName,
                     Value = i.ReligionId.ToString()
                 })

             };

            if (id == null || id == 0)
            {
                return NotFound();
            }

            deadVM.Dead = _db.Deads.Find(id);
            if (deadVM.Dead == null)
            {
                return NotFound();
            }

            return View(deadVM);
        }
                                                                                                                                                                                                                                                                                                                                                                            

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post Edit
        public IActionResult Edit(DeadVM obj)
        {
            if (ModelState.IsValid)
            {
                _db.Deads.Update(obj.Dead);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // Get Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id < 1)
            {
                return NotFound();
            }
            var obj = _db.Deads.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post Delete
        public IActionResult DeletePost(int? DeadId)
        {
            var obj = _db.Deads.Find(DeadId);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Deads.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RefTemeto/Views/Dead/Create.cshtml
@model RefTemeto.Models.ViewModels.DeadVM

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Elhunyt adatainak felvétele</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBirthLastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadBirthLastName" class="form-control" />
                        <span asp-validation-for="Dead.DeadBirthLastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBirthFirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadBirthFirstName" class="form-control" />
                        <span asp-validation-for="Dead.DeadBirthFirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadMothersName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadMothersName" class="form-control" />
                        <span asp-validation-for="Dead.DeadMothersName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBirthSettlementId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Dead.DeadBirthSettlementId" asp-items="@Model.TypeDropDownSettlement" class="form-control">
                            <option selected>-- Válasszon születési helyet!--</option>
                        </select>
                        <span asp-validation-for="Dead.DeadBirthSettlementId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBirthDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadBirthDate" class="form-control" />
                        <span asp-validation-for="Dead.DeadBirthDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadDeathDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadDeathDate" class="form-control" />
                        <span asp-validation-for="Dead.DeadDeathDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadReligionId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Dead.DeadReligionId" asp-items="@Model.TypeDropDownReligion" class="form-control">
                            <option selected>-- Válasszon születési helyet!--</option>
                        </select>
                        <span asp-validation-for="Dead.DeadReligionId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadCauseOfDeath"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadCauseOfDeath" class="form-control" />
                        <span asp-validation-for="Dead.DeadCauseOfDeath" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadGraveId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Dead.DeadGraveId" asp-items="@Model.TypeDropDownGrave" class="form-control">
                            <option selected>-- Válasszon sírhelyet!--</option>
                        </select>
                        <span asp-validation-for="Dead.DeadGraveId" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBurialId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Dead.DeadBurialId" asp-items="@Model.TypeDropDownBurial" class="form-control">
                            <option selected>-- Válasszon temetést!--</option>
                        </select>
                        <span asp-validation-for="Dead.DeadBurialId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Felvesz" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>

    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Dead/Delete.cshtml
@model RefTemeto.Models.Dead

<form method="post" asp-action="DeletePost">
    <input asp-for="DeadId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Elhunyt adatainak törlése</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DeadBirthLastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DeadBirthLastName" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DeadBirthFirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DeadBirthFirstName" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DeadMothersName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DeadMothersName" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DeadBirthDate "></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DeadBirthDate " disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DeadDeathDate "></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DeadDeathDate " disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DeadCauseOfDeath "></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DeadCauseOfDeath  " disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Töröl" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Dead/Edit.cshtml
@model RefTemeto.Models.ViewModels.DeadVM

<form method="post">
    <input asp-for="Dead.DeadId" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Elhunyt adatinak módosítása</h2>
        </div>
        <div class="row">
            <div class="col-8">

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBirthLastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadBirthLastName" class="form-control" />
                        <span asp-validation-for="Dead.DeadBirthLastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBirthFirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadBirthFirstName" class="form-control" />
                        <span asp-validation-for="Dead.DeadBirthFirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadMothersName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadMothersName" class="form-control" />
                        <span asp-validation-for="Dead.DeadMothersName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBirthSettlementId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Dead.DeadBirthSettlementId" asp-items="@Model.TypeDropDownSettlement" class="form-control">
                            <option selected>-- Válasszon születési helyet!--</option>
                        </select>
                        <span asp-validation-for="Dead.DeadBirthSettlementId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBirthDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadBirthDate" class="form-control" />
                        <span asp-validation-for="Dead.DeadBirthDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadDeathDate"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadDeathDate" class="form-control" />
                        <span asp-validation-for="Dead.DeadDeathDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadReligionId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Dead.DeadReligionId" asp-items="@Model.TypeDropDownReligion" class="form-control">
                            <option selected>-- Válasszon születési helyet!--</option>
                        </select>
                        <span asp-validation-for="Dead.DeadReligionId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadCauseOfDeath"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Dead.DeadCauseOfDeath" class="form-control" />
                        <span asp-validation-for="Dead.DeadCauseOfDeath" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadGraveId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Dead.DeadGraveId" asp-items="@Model.TypeDropDownGrave" class="form-control">
                            <option selected>-- Válasszon sírhelyet!--</option>
                        </select>
                        <span asp-validation-for="Dead.DeadGraveId" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8">
                        <label asp-for="Dead.DeadBurialId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Dead.DeadBurialId" asp-items="@Model.TypeDropDownBurial" class="form-control">
                            <option selected>-- Válasszon temetést!--</option>
                        </select>
                        <span asp-validation-for="Dead.DeadBurialId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Frissít" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>

                <div class="col-4">
                    @* Keep this empty *@
                </div>
            </div>
            </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Dead/Index.cshtml
@model IEnumerable<RefTemeto.Models.Dead>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Elhunytak listája</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Dead" asp-action="Create" class="btn btn-primary">
                Új elhunyt felvétele
            </a>
        </div>
    </div>
    <br /> <br />

    @if (Model.Count() > 0)
    {
        <table class="table-bordered table-striped" style="width: 100%">
            <thead>
                <tr>
                    <th>
                        Név
                    </th>
                    <th>
                        Anyja neve
                    </th>
                    <th>
                        Születési hely
                    </th>
                    <th>
                        Születési dátum
                    </th>
                    <th>
                        Sírhely
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="15%"> @obj.DeadBirthLastName @obj.DeadBirthFirstName       </td>
                    <td width="15%"> @obj.DeadMothersName                                 </td>
                    <td width="15%"> @obj.Settlement.Station   @obj.Settlement.PostalCode </td>
                    <td width="15%"> @obj.DeadBirthDate       </td>
                    <td width="15%"> @obj.Grave.Row. sor, @obj.Grave.Side oldal, @obj.Grave.Parcel. parcella, @obj.Grave.GraveType típus, @obj.Grave.Size méret </td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Dead" asp-route-Id="@obj.DeadId" asp-action="Edit" class="btn btn-primary mx-2">
                                Szerkeszt
                            </a>
                            <a asp-controller="Dead" asp-route-Id="@obj.DeadId" asp-action="Delete" class="btn btn-danger mx-2">
                                Töröl
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Nincsenek rögzített elhunytak.</p>
    }
</div>