RefTemeto/Models/Settlement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RefTemeto.Models
{
    public class Settlement                 //Irányítószámok
    {
        [Key]
        public int SettlementId { get; set; }
        [Required]
        [DisplayName("Irányítószám")]
        public int PostalCode { get; set; }

        [Required]
        [DisplayName("Település")]
        public string Station { get; set; }

    }
}

RefTemeto/Controllers/SettlementController.cs
using Microsoft.AspNetCore.Mvc;
using RefTemeto.Data;
using RefTemeto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RefTemeto.Controllers
{
    public class SettlementController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SettlementController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Settlement> objList = _db.Settlements;
            return View(objList);
        }

        //GET-CREATE
        public IActionResult Create()
        {
            return View();
        }

        //Post-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Settlement obj)
        {
            if (ModelState.IsValid)
            {
                _db.Settlements.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Settlements.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post Edit
        public IActionResult Edit(Settlement obj)
        {
            if (ModelState.IsValid)
            {
                _db.Settlements.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // Get Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id < 1)
            {
                return NotFound();
            }
            var obj = _db.Settlements.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post Delete
        public IActionResult DeletePost(int? SettlementId)
        {
            var obj = _db.Settlements.Find(SettlementId);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Settlements.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RefTemeto/Views/Settlement/Create.cshtml
@model RefTemeto.Models.Settlement

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Település felvétele</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PostalCode"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PostalCode" class="form-control" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Station"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Station" class="form-control" />
                        <span asp-validation-for="Station" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Felvesz" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>

    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Settlement/Delete.cshtml
@model RefTemeto.Models.Settlement

<form method="post" asp-action="DeletePost">
    <input asp-for="SettlementId" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3"> Település törlése </h2>
        </div>
        <div class="row">
            <div class="col-8">

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Station"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Station" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PostalCode"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PostalCode" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Töröl" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Settlement/Edit.cshtml
@model RefTemeto.Models.Settlement

<form method="post">
    <input asp-for="SettlementId" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Település adatainak módosítása</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PostalCode"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PostalCode" class="form-control" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Station"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Station" class="form-control" />
                        <span asp-validation-for="Station" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Frissít" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Vissza </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>

    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

RefTemeto/Views/Settlement/Index.cshtml
@model IEnumerable<RefTemeto.Models.Settlement>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-8">
            <h2 class="text-primary">Magyarországon található települések irányítószámai</h2>
        </div>
        <div class="col-4 text-right">
            <a asp-controller="Settlement" asp-action="Create" class="btn btn-primary">
                Új település felvétele
            </a>
        </div>
    </div>
    <br /> <br />

    @if (Model.Count() > 0)
    {
        <table class="table-bordered table-striped" style="width: 70%">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Irányítószám
                    </th>
                    <th>
                        Település
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="20%"> @obj.SettlementId      </td>
                    <td width="20%"> @obj.PostalCode        </td>
                    <td width="30%"> @obj.Station           </td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Settlement" asp-route-Id="@obj.SettlementId" asp-action="Edit" class="btn btn-primary mx-2">
                                Szerkeszt
                            </a>
                            <a asp-controller="Settlement" asp-route-Id="@obj.SettlementId" asp-action="Delete" class="btn btn-danger mx-2">
                                Töröl
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Nincsenek megjeleníthető adatok.</p>
    }
</div>